pool:
  name: Default

jobs:
  - job: Build
    steps:
      - task: Bash@3
        displayName: "Install dependencies"
        inputs:
          targetType: 'inline'
          script: 'npm ci'
          workingDirectory: tests/

      - task: AzureCLI@2
        displayName: Run Playwright Test
        env:
          PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
        inputs:
          azureSubscription: 'lydiakarungi'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            export PLAYWRIGHT_SERVICE_RUN_ID="run-$(date +%s)"
            echo "Using Run ID: $PLAYWRIGHT_SERVICE_RUN_ID"
            PLAYWRIGHT_SERVICE_RUN_ID=$PLAYWRIGHT_SERVICE_RUN_ID npx playwright test --config=playwright.service.config.js
          addSpnToEnvironment: true

      - task: PublishPipelineArtifact@1
        displayName: Upload Playwright report
        inputs:
          targetPath: tests/playwright-report/
          artifact: 'Playwright tests'
          publishLocation: 'pipeline'