pool:
  name: Default

jobs:
  - job: Build
    steps:
      - task: Bash@3
        displayName: "Install dependencies"
        inputs:
          targetType: 'inline'
          script: 'npm ci'
          workingDirectory: tests/

      - task: AzureCLI@2
        displayName: Run Playwright Test
        env:
          PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
          PLAYWRIGHT_SERVICE_RUN_ID: $(Build.DefinitionName) - $(Build.BuildNumber) - $(System.JobAttempt)
        inputs:
          azureSubscription: 'lydiakarungi'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            npx playwright test ClientApp.spec.js --config=playwright.service.config.js
          addSpnToEnvironment: true

      - task: PublishPipelineArtifact@1
        displayName: Upload Playwright report
        inputs:
          targetPath: tests/playwright-report/
          artifact: 'Playwright tests'
          publishLocation: 'pipeline'